### ISSUE TITLE
Crashing: failed to compress JPG

### ISSUE THREAD

**Issue by wilsonCernWq** [Twinklebear/module_pidx#3]
I found the module crashed when loading data
```
qwu@kepler16 [build]: mpirun -np 16 ./pidx_render_worker -dataset ~/data/PIDX_CoalBoiler/CCVars.idx -timestep 229829 -port 12345 -variable O2
Now listening for client on kepler16:12345
currentimestep = 229829
Variable count = 51
Volume dimensions: (1466,638,578)
Variable type name: 1*float32
Values per sample: 1
Bits per sample: 32
PIDX_RAW_IO /home/sci/qwu/data/PIDX_CoalBoiler/CCVars.idx
[RAW] [/home/sci/qwu/data/PIDX_CoalBoiler/CCVars.idx] [1466 638 578 : 64 64 64] [1] [T 229829 R 13 N 16 V 1] : [0.0000 + 0.0000 (0.0000 = 0.0000 + 0.0000 + 0.0000) = 0.0000] + 4.2160 [4.2160 24.7899]
Rank 5 load time: 20574ms
Rank 8 load time: 20578ms
Rank 12 load time: 20577ms
Rank 14 load time: 20577ms
Rank 0 load time: 20575ms
Rank 1 load time: 20575ms
Rank 2 load time: 20575ms
Rank 3 load time: 20574ms
Rank 4 load time: 20575ms
Rank 6 load time: 20575ms
Rank 7 load time: 20575ms
Rank 9 load time: 20578ms
Rank 10 load time: 20578ms
Rank 11 load time: 20577ms
Rank 13 load time: 20578ms
Rank 15 load time: 20578ms
Value range = (-1.99799,1.99799)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to compress JPG!
```

**Comment by Twinklebear** [comment]
I'm not able to reproduce this with libjpeg-turbo-1.5.2, maybe try with the latest commits? It will call `tjGetErrStr` to get more error information about why it failed to compress/decompress. Maybe it's using some older version of turbojpeg?

Also be sure to pass `-ppn 1` to mpirun, otherwise it might be running all 16 procs on one node, instead of one process per node (check out the [sample slurm jobscript](https://github.com/Twinklebear/module_pidx/blob/master/run-viewer-slurm.sh))

**Comment by wilsonCernWq** [comment]
It seems problem solved by fixing the version mismatch. Maybe we should mention it in the README page.

BTW now we can put the directory name directly like `-timesteps ~/data/pidx_uintah` without telling the timestep ?

**Comment by Twinklebear** [comment]
Interesting, I would have thought the JPEG format would be fine to compress/decompress with any version, maybe there's some bug or I'm using some other flag which isn't supported in the other version.

Yea the timesteps thing I added recently, it will expect the Uintah INCITE directory structure of timesteps and will go through and get the list so you can browse through them. The structure should be:

```
folder/
    t0000001/
        l0/
            CCVars.idx
            CCVars/
            <etc...>
    t0000005/
        l0/
            CCVars.idx
            CCVars/
            <etc...>
```

**Comment by wilsonCernWq** [comment]
I think it is caused by OSPRay's recently update. My Ubuntu is working also.

**Comment by Twinklebear** [comment]
Added note in readme to clarify turbojpeg versions and build instructions in 76a6feb57194d1731a363927981f4872192ac1ac

**Comment by Twinklebear** [comment]
Ah the update to devel fixes a different crash related to some correctness in the template deduction for serializing data types over the fabric. That was fixed in https://github.com/ospray/ospray/commit/c684deaedc1ac3cddcef5a61aaf59c7f6557fdfc and cleaned up by Jeff in https://github.com/ospray/ospray/commit/e2085c529a5dcce7b56162246aae21b9f49962cc
